### ISSUE TITLE
Scanning for devices...No devices found

### ISSUE THREAD

**Issue by jakestmart** [ericellb/Broadlink-CLI-SmartIR#2]
Hi Thanks for creating a great tool!

I've followed your instructions, so far my terminal is showing:
➜  broadlink-CLI-SmartIR git:(master) ✗ pip3 install -r requirements.txt
Requirement already satisfied: broadlink==0.19.0 in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 1)) (0.19.0)
Requirement already satisfied: cffi==1.16.0 in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 2)) (1.16.0)
Requirement already satisfied: cryptography==42.0.5 in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 3)) (42.0.5)
Requirement already satisfied: prompt-toolkit==3.0.36 in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 4)) (3.0.36)
Requirement already satisfied: pycparser==2.22 in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 5)) (2.22)
Requirement already satisfied: questionary==2.0.1 in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 6)) (2.0.1)
Requirement already satisfied: wcwidth==0.2.13 in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 7)) (0.2.13)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
➜  broadlink-CLI-SmartIR git:(master) ✗ python src/main.py              
Scanning for devices...

No devices found

______________________
I've currently got 3 broadlink devices on my network:
- 2 x RM4 pro
- 1 x RM4 mini
________________
install location ~/config/cusom_components/broadlink-CLI-SmartIR

I've checked if they are visible on Home assistant and my network. I can ping the device on the network.
Any help would be appreciated. 

Thank you in advance

**Comment by ericellb** [comment]
You can ping the devices off the same machine that you're running the script on?

I've had no issue, so you need to provide more info. I beleive you also need to "unlock" the devices through the broadlink app for it to work.

**Comment by jakestmart** [comment]
Thank you for your support, I've been able to detect the devices using another program. Appreciate the effort.
